// Generated by https://quicktype.io

export type Match = {
  id: number;
  teamA: string;
  teamB: string;
  teamAimage: string;
  teamBimage: string;
  matchDate: string;
  betOffer: number;
  isDeleted: boolean;
  isMatchStarted: boolean;
  isBeted: boolean;
  result: string;
  isMatchFinished: boolean;
  deletedAt: null;
};
